/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Projects */
        get: operations["read_projects_api_projects_get"];
        put?: never;
        /** Create Project Endpoint */
        post: operations["create_project_endpoint_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Project */
        get: operations["read_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Archive Project Endpoint */
        patch: operations["archive_project_endpoint_api_projects__project_id__archive_patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Project Memberships */
        get: operations["read_project_memberships_api_projects__project_id__memberships_get"];
        put?: never;
        /** Upsert Project Membership Endpoint */
        post: operations["upsert_project_membership_endpoint_api_projects__project_id__memberships_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/memberships/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Project Membership Endpoint */
        delete: operations["delete_project_membership_endpoint_api_projects__project_id__memberships__user_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Tasks */
        get: operations["read_tasks_api_tasks_get"];
        put?: never;
        /** Create Task Endpoint */
        post: operations["create_task_endpoint_api_tasks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Task Endpoint */
        put: operations["update_task_endpoint_api_tasks__task_id__put"];
        post?: never;
        /** Delete Task Endpoint */
        delete: operations["delete_task_endpoint_api_tasks__task_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Archive Task Endpoint */
        patch: operations["archive_task_endpoint_api_tasks__task_id__archive_patch"];
        trace?: never;
    };
    "/api/tasks/{task_id}/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Task Context */
        get: operations["read_task_context_api_tasks__task_id__context_get"];
        put?: never;
        /** Create Task Context Endpoint */
        post: operations["create_task_context_endpoint_api_tasks__task_id__context_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Task Memory */
        get: operations["read_task_memory_api_tasks__task_id__memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/resume-packet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Task Resume Packet */
        get: operations["read_task_resume_packet_api_tasks__task_id__resume_packet_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tasks/{task_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Task Activity */
        get: operations["read_task_activity_api_tasks__task_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Dependencies */
        get: operations["read_dependencies_api_dependencies_get"];
        put?: never;
        /** Create Dependency Endpoint */
        post: operations["create_dependency_endpoint_api_dependencies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/dependencies/{dependency_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Dependency Endpoint */
        delete: operations["delete_dependency_endpoint_api_dependencies__dependency_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Memory Overview */
        get: operations["read_memory_overview_api_memory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/task-states": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Task Operational States */
        get: operations["read_task_operational_states_api_task_states_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workspace": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Workspace Snapshot */
        get: operations["read_workspace_snapshot_api_workspace_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/control-center": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Control Center Snapshot */
        get: operations["read_control_center_snapshot_api_control_center_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Activity Feed */
        get: operations["read_activity_feed_api_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Health */
        get: operations["read_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Ready */
        get: operations["read_ready_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Metrics */
        get: operations["read_metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Ops Config */
        get: operations["read_ops_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Live Events */
        get: operations["stream_live_events_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Project Endpoint */
        get: operations["export_project_endpoint_api_projects__project_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Project Endpoint */
        post: operations["import_project_endpoint_api_projects_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Backup Project Endpoint */
        post: operations["backup_project_endpoint_api_projects__project_id__backup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityEvent */
        ActivityEvent: {
            /** Id */
            id?: number | null;
            /** Event Type */
            event_type: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id?: number | null;
            /** Task Id */
            task_id?: number | null;
            /** Task Title */
            task_title?: string | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /**
             * Actor
             * @default System
             */
            actor: string;
            /**
             * Source
             * @default system
             */
            source: string;
            /** Project Id */
            project_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ActivityEventSnapshot */
        ActivityEventSnapshot: {
            /** Event Type */
            event_type: string;
            /** Entity Type */
            entity_type: string;
            /** Entity Id */
            entity_id?: number | null;
            /** Task Id */
            task_id?: number | null;
            /** Task Title */
            task_title?: string | null;
            /** Title */
            title: string;
            /** Summary */
            summary: string;
            /**
             * Actor
             * @default System
             */
            actor: string;
            /**
             * Source
             * @default system
             */
            source: string;
            /** Created At */
            created_at?: string | null;
        };
        /** AttentionTaskItem */
        AttentionTaskItem: {
            /** Task Id */
            task_id: number;
            /** Task Title */
            task_title: string;
            task_status: components["schemas"]["TaskStatus"];
            /**
             * Priority
             * @default medium
             */
            priority: string;
            /**
             * Is Blocked
             * @default false
             */
            is_blocked: boolean;
            /**
             * Blocked By Open Count
             * @default 0
             */
            blocked_by_open_count: number;
            /**
             * Missing Summary
             * @default false
             */
            missing_summary: boolean;
            /**
             * Missing Next Step
             * @default false
             */
            missing_next_step: boolean;
            /**
             * Recent Entries
             * @default 0
             */
            recent_entries: number;
            /** Latest Summary */
            latest_summary?: string | null;
            /** Latest Next Step */
            latest_next_step?: string | null;
        };
        /** ContextEntry */
        ContextEntry: {
            /** Id */
            id?: number | null;
            /** Task Id */
            task_id: number;
            /** Content */
            content: string;
            /**
             * Entry Type
             * @default note
             */
            entry_type: string;
            /** Summary */
            summary?: string | null;
            /** What Changed */
            what_changed?: string | null;
            /** Files Touched */
            files_touched?: string | null;
            /** Decisions */
            decisions?: string | null;
            /** Open Questions */
            open_questions?: string | null;
            /** Next Step */
            next_step?: string | null;
            /**
             * Actor
             * @default System
             */
            actor: string;
            /**
             * Source
             * @default system
             */
            source: string;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp?: string;
        };
        /** ContextEntryCreate */
        ContextEntryCreate: {
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Entry Type
             * @default handoff
             */
            entry_type: string;
            /** Summary */
            summary?: string | null;
            /** What Changed */
            what_changed?: string | null;
            /** Files Touched */
            files_touched?: string | null;
            /** Decisions */
            decisions?: string | null;
            /** Open Questions */
            open_questions?: string | null;
            /** Next Step */
            next_step?: string | null;
        };
        /** ContextEntrySnapshot */
        ContextEntrySnapshot: {
            /** Task Id */
            task_id: number;
            /**
             * Content
             * @default
             */
            content: string;
            /**
             * Entry Type
             * @default handoff
             */
            entry_type: string;
            /** Summary */
            summary?: string | null;
            /** What Changed */
            what_changed?: string | null;
            /** Files Touched */
            files_touched?: string | null;
            /** Decisions */
            decisions?: string | null;
            /** Open Questions */
            open_questions?: string | null;
            /** Next Step */
            next_step?: string | null;
            /**
             * Actor
             * @default System
             */
            actor: string;
            /**
             * Source
             * @default system
             */
            source: string;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** ControlCenterSnapshot */
        ControlCenterSnapshot: {
            /**
             * Generated At
             * Format: date-time
             */
            generated_at?: string;
            /**
             * Total Tasks
             * @default 0
             */
            total_tasks: number;
            /**
             * Todo Count
             * @default 0
             */
            todo_count: number;
            /**
             * In Progress Count
             * @default 0
             */
            in_progress_count: number;
            /**
             * Done Count
             * @default 0
             */
            done_count: number;
            /**
             * Ready Count
             * @default 0
             */
            ready_count: number;
            /**
             * Blocked Count
             * @default 0
             */
            blocked_count: number;
            /**
             * Handoff Gap Count
             * @default 0
             */
            handoff_gap_count: number;
            /**
             * Handoffs Last 7 Days
             * @default 0
             */
            handoffs_last_7_days: number;
            /** Ready Queue */
            ready_queue?: components["schemas"]["ReadyQueueItem"][];
            /** Attention Tasks */
            attention_tasks?: components["schemas"]["AttentionTaskItem"][];
            /** Latest Handoffs */
            latest_handoffs?: components["schemas"]["HandoffPulseItem"][];
            server?: components["schemas"]["MCPServerStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandoffPulseItem */
        HandoffPulseItem: {
            /** Task Id */
            task_id: number;
            /** Task Title */
            task_title: string;
            task_status: components["schemas"]["TaskStatus"];
            /** Summary */
            summary?: string | null;
            /** Next Step */
            next_step?: string | null;
            /** Timestamp */
            timestamp?: string | null;
        };
        /** MCPServerStatus */
        MCPServerStatus: {
            /**
             * Name
             * @default Nexus Context
             */
            name: string;
            /**
             * Transport
             * @default sse
             */
            transport: string;
            /**
             * Status
             * @default online
             */
            status: string;
            /**
             * Sse Url
             * @default /mcp/sse
             */
            sse_url: string;
            /**
             * Post Message Url
             * @default /mcp/messages
             */
            post_message_url: string;
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Owner User Id
             * @default default-user
             */
            owner_user_id: string;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ProjectArchiveUpdate */
        ProjectArchiveUpdate: {
            /** Archived */
            archived: boolean;
        };
        /** ProjectBackupResult */
        ProjectBackupResult: {
            /** Project Id */
            project_id: string;
            /** Backup File */
            backup_file: string;
            /** Backup Path */
            backup_path: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** ProjectExportBundle */
        "ProjectExportBundle-Input": {
            /**
             * Version
             * @default 2026-03-15
             */
            version: string;
            /**
             * Exported At
             * Format: date-time
             */
            exported_at?: string;
            project: components["schemas"]["ProjectSnapshot"];
            /** Memberships */
            memberships?: components["schemas"]["ProjectMembershipSnapshot"][];
            /** Tasks */
            tasks?: components["schemas"]["TaskSnapshot"][];
            /** Dependencies */
            dependencies?: components["schemas"]["TaskDependencySnapshot"][];
            /** Context Entries */
            context_entries?: components["schemas"]["ContextEntrySnapshot"][];
            /** Activity Events */
            activity_events?: components["schemas"]["ActivityEventSnapshot"][];
        };
        /** ProjectExportBundle */
        "ProjectExportBundle-Output": {
            /**
             * Version
             * @default 2026-03-15
             */
            version: string;
            /**
             * Exported At
             * Format: date-time
             */
            exported_at?: string;
            project: components["schemas"]["ProjectSnapshot"];
            /** Memberships */
            memberships?: components["schemas"]["ProjectMembershipSnapshot"][];
            /** Tasks */
            tasks?: components["schemas"]["TaskSnapshot"][];
            /** Dependencies */
            dependencies?: components["schemas"]["TaskDependencySnapshot"][];
            /** Context Entries */
            context_entries?: components["schemas"]["ContextEntrySnapshot"][];
            /** Activity Events */
            activity_events?: components["schemas"]["ActivityEventSnapshot"][];
        };
        /** ProjectImportRequest */
        ProjectImportRequest: {
            bundle: components["schemas"]["ProjectExportBundle-Input"];
            /** Target Project Id */
            target_project_id?: string | null;
            /**
             * Replace Existing
             * @default false
             */
            replace_existing: boolean;
            /**
             * Include Memberships
             * @default true
             */
            include_memberships: boolean;
        };
        /** ProjectImportResult */
        ProjectImportResult: {
            /** Project Id */
            project_id: string;
            /**
             * Replaced Existing
             * @default false
             */
            replaced_existing: boolean;
            /**
             * Imported Task Count
             * @default 0
             */
            imported_task_count: number;
            /**
             * Imported Dependency Count
             * @default 0
             */
            imported_dependency_count: number;
            /**
             * Imported Context Entry Count
             * @default 0
             */
            imported_context_entry_count: number;
            /**
             * Imported Activity Event Count
             * @default 0
             */
            imported_activity_event_count: number;
            /**
             * Imported Membership Count
             * @default 0
             */
            imported_membership_count: number;
        };
        /** ProjectMembership */
        ProjectMembership: {
            /** Id */
            id?: number | null;
            /** Project Id */
            project_id: string;
            /** User Id */
            user_id: string;
            /**
             * Role
             * @default member
             */
            role: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** ProjectMembershipCreate */
        ProjectMembershipCreate: {
            /** User Id */
            user_id: string;
            /**
             * Role
             * @default member
             */
            role: string;
        };
        /** ProjectMembershipSnapshot */
        ProjectMembershipSnapshot: {
            /** User Id */
            user_id: string;
            /**
             * Role
             * @default member
             */
            role: string;
            /** Created At */
            created_at?: string | null;
        };
        /** ProjectSnapshot */
        ProjectSnapshot: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Owner User Id
             * @default default-user
             */
            owner_user_id: string;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /** ReadyQueueItem */
        ReadyQueueItem: {
            /** Task Id */
            task_id: number;
            /** Task Title */
            task_title: string;
            /** Description */
            description?: string | null;
            task_status: components["schemas"]["TaskStatus"];
            /**
             * Priority
             * @default medium
             */
            priority: string;
            /** Labels */
            labels?: string | null;
            /** Latest Summary */
            latest_summary?: string | null;
            /** Latest Next Step */
            latest_next_step?: string | null;
            /**
             * Blocks Open Count
             * @default 0
             */
            blocks_open_count: number;
            /** Recent Files */
            recent_files?: string[];
            /**
             * Handoff Complete
             * @default false
             */
            handoff_complete: boolean;
        };
        /** RelatedTaskSummary */
        RelatedTaskSummary: {
            /** Task Id */
            task_id: number;
            /** Task Title */
            task_title: string;
            task_status: components["schemas"]["TaskStatus"];
            /** Dependency Type */
            dependency_type: string;
        };
        /** ResumePacket */
        ResumePacket: {
            task: components["schemas"]["Task"];
            task_state: components["schemas"]["TaskOperationalState"];
            memory: components["schemas"]["TaskMemorySummary"];
            /** Blocked By */
            blocked_by?: components["schemas"]["RelatedTaskSummary"][];
            /** Unblocks */
            unblocks?: components["schemas"]["RelatedTaskSummary"][];
            /**
             * Handoff Complete
             * @default false
             */
            handoff_complete: boolean;
            /** Recommended Next Actions */
            recommended_next_actions?: string[];
            /** Agent Brief */
            agent_brief: string;
        };
        /** Task */
        Task: {
            /** Id */
            id?: number | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default todo */
            status: components["schemas"]["TaskStatus"];
            /**
             * Priority
             * @default medium
             */
            priority: string;
            /** Labels */
            labels?: string | null;
            /** Project Id */
            project_id?: string | null;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
        /** TaskArchiveUpdate */
        TaskArchiveUpdate: {
            /** Archived */
            archived: boolean;
        };
        /** TaskCreate */
        TaskCreate: {
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default todo */
            status: components["schemas"]["TaskStatus"];
            /**
             * Priority
             * @default medium
             */
            priority: string;
            /** Labels */
            labels?: string | null;
            /** Project Id */
            project_id: string;
        };
        /** TaskDependency */
        TaskDependency: {
            /** Id */
            id?: number | null;
            /** Source Task Id */
            source_task_id: number;
            /** Target Task Id */
            target_task_id: number;
            /**
             * Type
             * @default blocks
             */
            type: string;
            /** Source Handle */
            source_handle?: string | null;
            /** Target Handle */
            target_handle?: string | null;
        };
        /** TaskDependencyCreate */
        TaskDependencyCreate: {
            /** Source Task Id */
            source_task_id: number;
            /** Target Task Id */
            target_task_id: number;
            /**
             * Type
             * @default blocks
             */
            type: string;
            /** Source Handle */
            source_handle?: string | null;
            /** Target Handle */
            target_handle?: string | null;
        };
        /** TaskDependencySnapshot */
        TaskDependencySnapshot: {
            /** Source Task Id */
            source_task_id: number;
            /** Target Task Id */
            target_task_id: number;
            /**
             * Type
             * @default blocks
             */
            type: string;
            /** Source Handle */
            source_handle?: string | null;
            /** Target Handle */
            target_handle?: string | null;
        };
        /** TaskMemorySummary */
        TaskMemorySummary: {
            /** Task Id */
            task_id: number;
            /** Task Title */
            task_title: string;
            task_status: components["schemas"]["TaskStatus"];
            /** Latest Summary */
            latest_summary?: string | null;
            /** Latest Next Step */
            latest_next_step?: string | null;
            /** Active Decisions */
            active_decisions?: string[];
            /** Open Questions */
            open_questions?: string[];
            /** Recent Files */
            recent_files?: string[];
            /** Recent Entries */
            recent_entries?: components["schemas"]["ContextEntry"][];
        };
        /** TaskOperationalState */
        TaskOperationalState: {
            /** Task Id */
            task_id: number;
            /**
             * Is Ready
             * @default false
             */
            is_ready: boolean;
            /**
             * Is Blocked
             * @default false
             */
            is_blocked: boolean;
            /**
             * Blocked By Open Count
             * @default 0
             */
            blocked_by_open_count: number;
            /**
             * Blocks Open Count
             * @default 0
             */
            blocks_open_count: number;
            /** Blocked By */
            blocked_by?: components["schemas"]["RelatedTaskSummary"][];
            /** Unblocks */
            unblocks?: components["schemas"]["RelatedTaskSummary"][];
        };
        /** TaskSnapshot */
        TaskSnapshot: {
            /** Id */
            id?: number | null;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** @default todo */
            status: components["schemas"]["TaskStatus"];
            /**
             * Priority
             * @default medium
             */
            priority: string;
            /** Labels */
            labels?: string | null;
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "todo" | "in_progress" | "done";
        /** TaskUpdate */
        TaskUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            status?: components["schemas"]["TaskStatus"] | null;
            /** Priority */
            priority?: string | null;
            /** Labels */
            labels?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkspaceSnapshot */
        WorkspaceSnapshot: {
            /** Tasks */
            tasks?: components["schemas"]["Task"][];
            /** Dependencies */
            dependencies?: components["schemas"]["TaskDependency"][];
            /** Memory */
            memory?: components["schemas"]["TaskMemorySummary"][];
            /** Task States */
            task_states?: components["schemas"]["TaskOperationalState"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_projects_api_projects_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_endpoint_api_projects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_project_endpoint_api_projects__project_id__archive_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectArchiveUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_project_memberships_api_projects__project_id__memberships_get: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMembership"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_project_membership_endpoint_api_projects__project_id__memberships_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectMembershipCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectMembership"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_membership_endpoint_api_projects__project_id__memberships__user_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                project_id: string;
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_tasks_api_tasks_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                include_archived?: boolean;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_endpoint_api_tasks_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_task_endpoint_api_tasks__task_id__put: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_task_endpoint_api_tasks__task_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_task_endpoint_api_tasks__task_id__archive_patch: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskArchiveUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_task_context_api_tasks__task_id__context_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextEntry"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_task_context_endpoint_api_tasks__task_id__context_post: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextEntry"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_task_memory_api_tasks__task_id__memory_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskMemorySummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_task_resume_packet_api_tasks__task_id__resume_packet_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumePacket"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_task_activity_api_tasks__task_id__activity_get: {
        parameters: {
            query?: {
                limit?: number;
                project_id?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                task_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_dependencies_api_dependencies_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDependency"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_dependency_endpoint_api_dependencies_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskDependencyCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDependency"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_dependency_endpoint_api_dependencies__dependency_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                dependency_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_memory_overview_api_memory_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                search?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskMemorySummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_task_operational_states_api_task_states_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOperationalState"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_workspace_snapshot_api_workspace_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_control_center_snapshot_api_control_center_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ControlCenterSnapshot"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_activity_feed_api_activity_get: {
        parameters: {
            query?: {
                limit?: number;
                project_id?: string | null;
                search?: string | null;
            };
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActivityEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_ready_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    read_metrics_metrics_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_ops_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    stream_live_events_events_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_project_endpoint_api_projects__project_id__export_get: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectExportBundle-Output"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_project_endpoint_api_projects_import_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backup_project_endpoint_api_projects__project_id__backup_post: {
        parameters: {
            query?: never;
            header?: {
                "x-nexus-user"?: string | null;
                "x-nexus-role"?: string | null;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectBackupResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
